# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# "OrdererOrgs" - 주문자 노드를 관리하는 조직의 정의
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer(주문자)
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description(전체 설명은 PeerOrgs 참조)
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes(피어 노드를 관리하는 조직의 정의)
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.com
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    # (구성에서 호스트의 명시적인 정의를 사용 가능하게하려면이 절의 주석 처리를 제거하십시오.
    #  대부분의 사용자는 아래의 템플릿을 사용하려고합니다.)
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    # (Specs는 Spec 항목의 배열입니다. 각 Spec 항목은 두 개의 필드로 구성됩니다.)
    #   - Hostname:   (Required) The desired hostname, sans the domain.
    #     ((필수) 원하는 호스트 이름은 도메인을 제외합니다.)
    #   - CommonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #     ((선택) CN에 대한 템플릿 또는 명시적 오버라이드를 지정합니다. 기본적으로 이는 템플릿입니다.) 
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    #                 (Spec.Hostname과 Org.Domain에서 해당 값을 각각 가져 오는 템플릿.)
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: foo # implicitly "foo.org1.example.com"
    #     CommonName: foo27.org5.example.com # overrides Hostname-based FQDN set above
    #                                        # (위에 설정된 호스트 이름 기반 FQDN을 무시합니다.)
    #   - Hostname: bar
    #   - Hostname: baz
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    # 템플릿에서 순차적으로 작성되는 하나 이상의 호스트를 정의 할 수 있습니다.
    # 기본적으로이 값은 0에서 Count-1까지의 "peer % d"와 같습니다.
    # 노드 수 (Count), 시작 인덱스 (Start) 또는 이름을 구성하는 데 사용된 템플릿(Hostname)을
    # 무시할 수 있습니다.
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # (노트 : 템플리트 및 스펙은 상호 배타적이지 않습니다.
    # 두 섹션을 모두 정의하면 집계 노드가 자동으로 생성됩니다. 이름 충돌에주의하십시오.)
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # (개수 : 관리자 이외의 사용자 계정 수)
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
